name: Test code before and after push to dev

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"


jobs:
  test_after_push:
    runs-on: ubuntu-latest
    steps:
      - name: pull git repo
        uses: actions/checkout@v2
