name: Test code before and after push to dev

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"


jobs:
  test_after_push:
    runs-on: ubuntu-latest
    steps:
      - name: pull git repo
        uses: actions/checkout@v2
      - name: install python version 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: unit test
        run: |
          pytest -v

